//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataDict
    {
        public int ID { get; set; }
        public Nullable<int> PARENTID { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public string VALUE { get; set; }
        public string CATEGORYCODE { get; set; }
        public string CATEGORYNAME { get; set; }
        public int ALLOWEDIT { get; set; }
        public int ALLOWDELETE { get; set; }
        public Nullable<int> SORTCODE { get; set; }
        public int DELETEMARK { get; set; }
        public int ENABLED { get; set; }
        public string DESCRIPTION { get; set; }
        public System.DateTime CREATEON { get; set; }
        public Nullable<int> CREATEUSERID { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> MODIFIEDON { get; set; }
        public Nullable<int> MODIFIEDUSERID { get; set; }
        public string MODIFIEDBY { get; set; }
    }
}
